# Generated by Django 5.2.1 on 2025-07-29 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number in format 2547XXXXXXXX', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_reference', models.CharField(max_length=50)),
                ('transaction_desc', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'M-Pesa Request',
                'verbose_name_plural': 'M-Pesa Requests',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MpesaResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('response_description', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_message', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='payments.mpesarequest')),
            ],
            options={
                'verbose_name': 'M-Pesa Response',
                'verbose_name_plural': 'M-Pesa Responses',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MpesaCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_code', models.CharField(max_length=10)),
                ('result_description', models.CharField(max_length=255)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('callback_metadata', models.JSONField(blank=True, help_text='Raw callback metadata from Safaricom', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='callback', to='payments.mpesaresponse')),
            ],
            options={
                'verbose_name': 'M-Pesa Callback',
                'verbose_name_plural': 'M-Pesa Callbacks',
                'ordering': ['-timestamp'],
            },
        ),
    ]
