# Generated by Django 5.2.1 on 2025-07-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('manager', 'Branch Manager'), ('storekeeper', 'Store Keeper'), ('salesperson', 'Sales Person'), ('staff', 'Staff'), ('customer', 'Customer')], default='staff', max_length=20),
        ),
    ]
