# Generated by Django 5.2.1 on 2025-07-30 11:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name', max_length=150)),
                ('contact_person', models.CharField(help_text='Primary contact person', max_length=100)),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('location', models.CharField(blank=True, help_text='Company location/address', max_length=200, null=True)),
                ('account_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Total account value in currency', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Active'), ('negotiation', 'Negotiation'), ('closed', 'Closed')], default='prospect', help_text='Current account status', max_length=20)),
                ('deals_count', models.PositiveIntegerField(default=0, help_text='Number of active deals')),
                ('last_contact_date', models.DateField(auto_now_add=True, help_text='Date of last contact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sales_accounts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Account',
                'verbose_name_plural': 'Sales Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Deal title/description', max_length=200)),
                ('value', models.DecimalField(decimal_places=2, help_text='Deal value', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('stage', models.CharField(choices=[('prospecting', 'Prospecting'), ('qualification', 'Qualification'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='prospecting', max_length=20)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('probability', models.PositiveIntegerField(default=0, help_text='Probability percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='salesaccounts.salesaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note'), ('proposal', 'Proposal Sent')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('activity_date', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_activities', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='salesaccounts.deal')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='salesaccounts.salesaccount')),
            ],
            options={
                'verbose_name': 'Contact Activity',
                'verbose_name_plural': 'Contact Activities',
                'ordering': ['-activity_date'],
            },
        ),
    ]
